### ISSUE TITLE
New Xplus3 update issue

### ISSUE THREAD

**Issue by baron011182** [QIDITECH/QIDI_PLUS3#40]
I have updated the printer today using the new release build for this device and I have encountered an issue.  

When I updated it I got a bank screen mentioning Data Error.  I managed to recover it but now I'm getting the following error on the screen and when http into the printer.  

Include file '/home/mks/klipper_config/MKS_THR.cfg' does not exist

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

This is on the new build that Qidi released 15hrs ago.  How do I fix this issue.

**Comment by baron011182** [comment]
![9973D552-7E12-4DC3-A7B9-1408BED9710E](https://github.com/user-attachments/assets/5dd0c438-542b-4fc7-a007-8652fc7b413d)

**Comment by TrollPlayer94** [comment]
How did you manage to recover from the DATA ERROR because nothing is working for me?

**Comment by svalsorim** [comment]
I just have white screen after the latest update, i think I just got message update failed check message. What message? Where? Also looking for a way to recover it but i have no working screen anymore

**Comment by baron011182** [comment]
I managed to get the screen working by using the QD_Plus3_UI5.0 and renaming it to mksscreen.recovery and putting that file onto a usb stick.  Enter the usb stick in the printer usb port and switch on.  It will do a re-flash on the screen to get that working.

**Comment by TrollPlayer94** [comment]
I got too this screen now to after trying this fix, but don't know how to proceed further.

**Comment by baron011182** [comment]
I think this has corrupted the klipper and moon raker folder under /home/mks/

Once I ssh into it using mobxterm and copied the files over from qidi own version of Klipper and moon raker I was able to get working again.

**Comment by svalsorim** [comment]
Great! Thank you for the update ill try that!

**Comment by svalsorim** [comment]
Mine will not accept mksscreen.recovery no matter what i do. I could access it via network but now I lost that too

**Comment by QIDITECH** [comment]
According to your description, I think it is caused by your updating of klipper or moonraker. Restoring it to the default version of firmware should solve the problem.

**Comment by baron011182** [comment]
Considering I’ve not updated klipper or moonraker.  Only your firmware.  This update is what caused me the issue.  Sent from my iPhoneOn 21 Oct 2024, at 03:22, QIDI TECH ***@***.***> wrote:﻿
According to your description, I think it is caused by your updating of klipper or moonraker. Restoring it to the default version of firmware should solve the problem.

**Comment by Plexix** [comment]
I don't understand how Qidi could release such a firmware version like 4.2.15. Not only does it cause the screen to freeze with a white screen of death, but if a user manages to recover using a micro SD card, there's a risk of damaging the printer. While the procedure with the micro SD card may resolve the white screen issue, it doesn't fix the underlying problems with the firmware itself. After switching to version 4.2.15 and performing the initial calibration, like input shaping and setting the Z offset, the printer completely ignores these settings during printing. If you start a print with mesh bed leveling, the printer immediately begins to dig the nozzle into the bed during the initial test line. First, I dealt with the frozen white screen, and now I've damaged my print bed. Qidi can't be serious about this.

**Comment by baron011182** [comment]
I had this issue too.  Qidi is not taking this one serious.  Always the end user fault which is not the case here.

**Comment by svalsorim** [comment]
I was going to comment that none of us updated klipper but used official update, but I left it to OP to address it. I’m still dealing with white screen and “data error! “ message.

**Comment by whb0514** [comment]
> ![9973D552-7E12-4DC3-A7B9-1408BED9710E](https://private-user-images.githubusercontent.com/98152266/377579467-5dd0c438-542b-4fc7-a007-8652fc7b413d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NTgwNDYsIm5iZiI6MTcyOTU1Nzc0NiwicGF0aCI6Ii85ODE1MjI2Ni8zNzc1Nzk0NjctNWRkMGM0MzgtNTQyYi00ZmM3LWEwMDctODY1MmZjN2I0MTNkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwMDQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTMzN2ZiNmFkYWRkY2JmYzk4ZDZlMDcyYzBjM2U2OGZlNjMwNWQxZmE2MzllYjM1MzI1OTIwY2QwYTUyOTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cKrlt_puIaHR5ch3fk8oIzVzw17oPc6NMG_MOSf1Dt8)

Just need the parameter page in the fluidd page, create a MKS_THR.cfg file, save it, and restart the machine to solve this problem. As for why the file is missing, we will look for the reason.

**Comment by baron011182** [comment]
Qidi have now gone quiet 🤐.  Can we have some support and at least pull this firmware from your firmware page.  This needs to be looked at and recompiled for the xplus 3.Sent from my iPhoneOn 22 Oct 2024, at 01:59, whb0514 ***@***.***> wrote:﻿



Just need the parameter page in the fluidd page, create a MKS_THR.cfg file, save it, and restart the machine to solve this problem. As for why the file is missing, we will look for the reason.

**Comment by herby99999** [comment]
> > ![9973D552-7E12-4DC3-A7B9-1408BED9710E](https://private-user-images.githubusercontent.com/98152266/377579467-5dd0c438-542b-4fc7-a007-8652fc7b413d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NTgwNDYsIm5iZiI6MTcyOTU1Nzc0NiwicGF0aCI6Ii85ODE1MjI2Ni8zNzc1Nzk0NjctNWRkMGM0MzgtNTQyYi00ZmM3LWEwMDctODY1MmZjN2I0MTNkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwMDQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTMzN2ZiNmFkYWRkY2JmYzk4ZDZlMDcyYzBjM2U2OGZlNjMwNWQxZmE2MzllYjM1MzI1OTIwY2QwYTUyOTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cKrlt_puIaHR5ch3fk8oIzVzw17oPc6NMG_MOSf1Dt8)
> 
> Um dieses Problem zu lösen, benötigen Sie lediglich die Parameterseite auf der Fluidd-Seite, erstellen eine MKS_THR.cfg-Datei, speichern sie und starten den Computer neu. Wir werden nach dem Grund suchen, warum die Datei fehlt.

kann den link nicht öffnen wäre dankbar damit der weiße screen weg geht

**Comment by gptech2444** [comment]
Wish I read this before doing the update. This is ridiculous. Now I have to try and unbrick my printer.
![image](https://github.com/user-attachments/assets/b15fb9f3-c7ef-485e-8802-3f40a3ddf159)

**Comment by mane81** [comment]
I am experiencing the same issue. Please remove this firmware release and correct it.

**Comment by baron011182** [comment]
Qidi are now totally ignoring this thread.  Sent from my iPhoneOn 25 Oct 2024, at 14:10, mane81 ***@***.***> wrote:﻿
I am experiencing the same issue. Please remove this firmware release and correct it.

**Comment by logiclinux** [comment]
I have just updatet to .Ver 4.2.15 got a blank screen but acces to the Printer via SSH. Then i found the solution to download the file 800_480_PLUS.tft on an sdcard and put this card into the cardslot at the Qidi X-Plus 3 screen (very complicated to reach i had to unscem the screen to rech the slot)  Swiching off wait 30 sec. swich on and it installs the frimware for the Screen.
But now i have no more access to the Network adjust,ments via this screen but you see the softkey gets pressed (at the moment no need caus its connected very well via ethernet and wifi). So i have SOC Ver 4.2.15 amd UI Ver 4.2.13  MMC is mot diplayed . When the srenn goes isn sctreensaver mode i cant wake him up by touching it.

**Comment by svalsorim** [comment]
For the record, I had not the same problem as the OP, I just had white screen( UI part failed) I got it resolved by repeated mksscreen.recovery updated in my case 5th consecutive time update passed. Maybe try forcing the update few times to see will it resolve your issue. There is a write up in wiki page for a Qidi q1 pro what to do if update failed.

**Comment by JozephSchmoe** [comment]
I was able to get past the white screen issues only to run into the Z offset problems. In my case, using the screen to set the Z offset results in a ridiculous -2.68 value. Adding 2mm to that value, for -.68 got me pretty close to what the value should be. This is far from ideal but I can at least print. You'll want to edit the config.mksini file, for anyone who didn't learn that from the last disastrous firmware update.
Do a reboot and Fluuid should see the correct value.
![Screenshot 3](https://github.com/user-attachments/assets/62803d83-cc30-47f8-9423-4893af583832)
